### ISSUE TITLE
kratos: No authentication in /___graphql

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#1853]
With the new authentication [`/___graphql`](https://de.serlo-staging.dev/___graphql) does not work any more (executing mutations which need a login fire a `you are not logged in error`):

```graphql
{
  media {
    newUpload(mediaType: IMAGE_PNG) {
      uploadUrl
    }
  }
}
```

results in

```
{
  "errors": [
    {
      "message": "You are not logged in",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "media",
        "newUpload"
      ],
      "extensions": {
        "code": "UNAUTHENTICATED",
        "exception": {
          "stacktrace": [
            "AuthenticationError: You are not logged in",
            "    at assertUserIsAuthenticated (/usr/src/app/packages/server/dist/api.serlo.org.cjs.development.js:2038:11)",
            "    at Object.newUpload (/usr/src/app/packages/server/dist/api.serlo.org.cjs.development.js:5596:7)",
            "    at field.resolve (/usr/src/app/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:56:26)",
            "    at executeField (/usr/src/app/node_modules/graphql/execution/execute.js:481:20)",
            "    at executeFields (/usr/src/app/node_modules/graphql/execution/execute.js:413:20)",
            "    at completeObjectValue (/usr/src/app/node_modules/graphql/execution/execute.js:914:10)",
            "    at completeValue (/usr/src/app/node_modules/graphql/execution/execute.js:635:12)",
            "    at completeValue (/usr/src/app/node_modules/graphql/execution/execute.js:584:23)",
            "    at executeField (/usr/src/app/node_modules/graphql/execution/execute.js:489:19)",
            "    at executeFields (/usr/src/app/node_modules/graphql/execution/execute.js:413:20)",
            "    at executeOperation (/usr/src/app/node_modules/graphql/execution/execute.js:344:14)",
            "    at execute (/usr/src/app/node_modules/graphql/execution/execute.js:136:20)",
            "    at execute (/usr/src/app/node_modules/apollo-server-core/dist/requestPipeline.js:205:48)",
            "    at processGraphQLRequest (/usr/src/app/node_modules/apollo-server-core/dist/requestPipeline.js:148:34)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by hugotiburtino** [comment]
At the moment, you should be testing it in https://\<beta-testing-custom-domain-for-user-management\>/___graphql
(for the custom domain, see beta-testing doc).
I've tested with your staging account and it works. So, closing it because it isn't a real issue.
